### PR TITLE
Transition before triggers to after. Security definers have explicit search_path

### LINKED ISSUE #29: Should `search_path` be set due to use of `SECURITY DEFINER`
# Chore

## Describe the chore

I was just reading the [documentation for CREATE FUNCTION in postgres](https://www.postgresql.org/docs/9.3/sql-createfunction.html), and I see the following section:

> ### Writing SECURITY DEFINER Functions Safely
>
> Because a SECURITY DEFINER function is executed with the privileges of the user that created it, care is needed to ensure that the function cannot be misused. For security, [search_path](https://www.postgresql.org/docs/9.3/runtime-config-client.html#GUC-SEARCH-PATH) should be set to exclude any schemas writable by untrusted users. 

## Additional context

I was just wondering if `search_path` should be set for the `SECURITY_DEFINER` functions in `supa_audit`. I am not a postgres expert, so if this isn't necessary for this repository, I would like to learn why not.

### LINKED ISSUE #38: Triggers should be `after`
Thanks for publishing this, Supabase! I am not a user, but I am a fan! I have used this as a starter for an audit log.

I think the triggers should be updated to `after` variant, not the `before` it is now. Or was there a reason that I do not see for using `before`?

When using `INSERT ... ON CONFLICT DO UPDATE SET ...` statement, the before trigger also tracks inserts, even if the effective change that should be tracked is the update part.

### PR DESCRIPTION
**Pull request by olirice**
## What kind of change does this PR introduce?
- Changes before triggers to after triggers to handle `on conflict` and computed columns correctly. resolves #38 
- Adds an explicit `search_path` to security definer functions. resolves #29
- Releases ^ updates as version `0.3.0`

### CODE REVIEW

**Comment by olirice** [comment]
@janm6k @msdrigg
if possible, could you please test this against (a copy of) one of your projects with some existing tables under audit?

**Comment by janm6k** [comment]
The code changes looks good @olirice! I don't have this deployed anywhere to test, I only used this repo as an inspiration.

**Review by michelp — APPROVED** [review]
Nice!

**Comment by msdrigg** [comment]
@olirice I am sorry but I don't have an easy way I can test this currently. All my supabase deployments are hosted. Is there an easy way to test this on hosted supabase?

**Comment by olirice** [comment]
no worries mgdrigg, we got it tested. thank you

**Pull request merged**
